default:
  image: docker:stable
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY/$CI_PROJECT_PATH
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$PHP_VERSION -f $DOCKERFILE_FILENAME .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$PHP_VERSION

variables:
  DOCKERFILE_FILENAME: 'Dockerfile'
  PHP_VERSION: 'latest'

stages:
  - build

build_php_81:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_81'
    PHP_VERSION: '8.1'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_80:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_80'
    PHP_VERSION: '8.0'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_74:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_74'
    PHP_VERSION: '7.4'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_73:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_73'
    PHP_VERSION: '7.3'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_72:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_72'
    PHP_VERSION: '7.2'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_71:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_71'
    PHP_VERSION: '7.1'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_70:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_70'
    PHP_VERSION: '7.0'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_56:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_56'
    PHP_VERSION: '5.6'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_55:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_55'
    PHP_VERSION: '5.5'
  script:
    echo "build $DOCKERFILE_FILENAME done!"

build_php_54:
  stage: build
  only:
    - master
  variables:
    DOCKERFILE_FILENAME: 'Dockerfile_54'
    PHP_VERSION: '5.4'
  script:
    echo "build $DOCKERFILE_FILENAME done!"
